RealKruGameWebsite/Pages/Works/Work.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkModels.Models;
using WorkServices.Services;

namespace RealKruGameWebsite.Pages.Works
{
    public class WorkModel : PageModel
    {
        private readonly IWorkRepository workRepository;
        public IEnumerable<Work> Works { get; set; }
        [BindProperty(SupportsGet =true)]
        public string SearchTerm { get; set; }

        public WorkModel(IWorkRepository workRepository)
        {
            this.workRepository = workRepository;
        }
        
        public void OnGet()
        {
            Works = workRepository.Search(SearchTerm);
        }
    }
}

RealKruGameWebsite/Pages/Works/WorkDelete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkModels.Models;
using WorkServices.Services;

namespace RealGameWebsiteTest.Pages.Works
{
    public class WorkDeleteModel : PageModel
    {

        private readonly IWorkRepository workRepository;
        public WorkDeleteModel(IWorkRepository workRepository)
        {
            this.workRepository = workRepository;
        }

        [BindProperty]
        public Work Work { get; set; }

        public IActionResult OnGet(int id)
        {
            Work = workRepository.GetWork(id);

            if (Work == null)
            {
                return RedirectToPage("/NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            Work DeletedWork = workRepository.Delete(Work.Id);

            if (Work == null)
            {
                return RedirectToPage("/NotFound");
            }
            return RedirectToPage("Work");
        }
    }
}

RealKruGameWebsite/Pages/Works/WorkDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkModels.Models;
using WorkServices.Services;

namespace RealKruGameWebsite.Pages.Works
{
    public class WorkDetailsModel : PageModel
    {
        private readonly IWorkRepository workRepository;

        public WorkDetailsModel(IWorkRepository workRepository)
        {
            this.workRepository = workRepository;
        }

        public Work Work { get; private set; }

        public void OnGet(int id)
        {
            Work = workRepository.GetWork(id);
        }
    }
}

RealKruGameWebsite/Pages/Works/WorkEdit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkModels.Models;
using WorkServices.Services;

namespace RealKruGameWebsite.Pages.Works
{
    public class WorkEditModel : PageModel
    {
        private readonly IWorkRepository workRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public WorkEditModel (IWorkRepository workRepository, IWebHostEnvironment webHostEnvironment)
        {
            this.workRepository = workRepository;
            // IWebHostEnvironment service allows us to get the
            // absolute path of WWWRoot folder
            this.webHostEnvironment = webHostEnvironment;
        }

        // This is the property the display template will use to
        // display existing Work data

        [BindProperty]
        public Work Work { get; set; }

        // We use this property to store and process
        // the newly uploaded photo

        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public bool Notify { get; set; }

        [TempData]
        public string Message { get; set; }

        // Populate Employee property
        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                Work = workRepository.GetWork(id.Value);
            }
            else
            {
                Work = new Work();
            }

            if (Work == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    // If a new photo is uploaded, the existing photo must be
                    // deleted. So check if there is an existing photo and delete
                    if (Work.PhotoPath != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath,
                            "workimages", Work.PhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    // Save the new photo in wwwroot/images folder and update
                    // PhotoPath property of the employee object
                    Work.PhotoPath = ProcessUploadedFile();
                }

                if(Work.Id > 0)
                {
                    Work = workRepository.Update(Work);
                }
                else
                {
                    Work = workRepository.Add(Work);
                }
                return RedirectToPage("/works/work");
            }
            return Page();
        }

        public IActionResult OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications";
            }
            else
            {
                Message = "You turned off notifications";
            }

            TempData["message"] = Message;

            return RedirectToPage("WorkDetails", new { id = id });
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "workimages");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

RealKruGameWebsite/Pages/Works/Work.cshtml
@page
@model RealKruGameWebsite.Pages.Works.WorkModel
@{
    ViewData["Title"] = "Work page";
}

<style>
    .btn {
        width: 75px;
    }
</style>

<h1>Works</h1>

<form method="get">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<div class="text-center">
    <a asp-page="/Works/WorkEdit"
       class="btn btn-primary m-1">Add Work</a>
</div>

<div class="card-deck">
    @foreach (var work in Model.Works)
    {
        var photoPath = "~/workimages/" + (work.PhotoPath ?? "noimage.png");
        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <div class="card-header">
                <h3>@work.Title</h3>
            </div>

            <img class="card-img-top imageThumbnail" src="@photoPath"
                 asp-append-version="true" />

            <div class="card-footer text-center">
                <a asp-page="/Works/WorkDetails" asp-route-ID="@work.Id"
                   class="btn btn-primary m-1">View</a>
                <a asp-page="/Works/WorkEdit" asp-route-ID="@work.Id"
                   class="btn btn-primary m-1">Edit</a>
                <a asp-page="/Works/WorkDelete" asp-route-ID="@work.Id"
                   class="btn btn-danger m-1">Delete</a>
            </div>
        </div>

    }
</div>

<div>
    <h4>Single File Upload (JS)</h4>
    <input type="file" onchange="UploadFile(event)" />
</div>


<div>
    <h4>Multiple File Upload (JS)</h4>
    <input type="file" multiple onchange="UploadFiles(event)" />
</div>

@section scripts {
    <script>
        var UploadFile = function (e) {
            var file = e.target.files[0];
            var formData = new FormData();
            formData.append("file", file);
            axios.post("/Home/SingleFile", formData);
        }
        var UploadFiles = function (e) {
            var files = e.target.files;
            var formData = new FormData();
            for (var i = 0; i < files.length; i++) {
                formData.append("files", files[i]);
            }
            axios.post("/Home/MultipleFiles", formData);
        }
        var UploadFileToModel = function (e) {
            var fileName = document.getElementById("file-name").value
            var file = e.target.files[0];
            var formData = new FormData();
            formData.append("someForm.Name", fileName);
            formData.append("someForm.File", file);
            axios.post("/Home/FileInModel", formData);
        }
    </script>
}

RealKruGameWebsite/Pages/Works/WorkDelete.cshtml
@page "{id}"
@model RealGameWebsiteTest.Pages.Works.WorkDeleteModel
@{
}

<h1>Delete Confirmation</h1>

<div class="alert alert-danger">
     <h5>Are you sure you want to delete @Model.Work.Title?</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a class="btn btn-primary" asp-page="/works/work">No</a>
    </form>
     </div>

RealKruGameWebsite/Pages/Works/WorkDetails.cshtml
@page
@model RealKruGameWebsite.Pages.Works.WorkDetailsModel
@{
    ViewData["Title"] = "Details";
    var photoPath = "~/workimages/" + (Model.Work.PhotoPath ?? "noimage.png");
}

<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.Work.Title</h1>
            </div>

            <div class="card-body text-center">
                <img class="card-img-top" src="@photoPath" asp-append-version="true" />
                <h4>@Model.Work.Description</h4>
                <h4>Start: @Model.Work.StartDate</h4>
                <h4>End: @Model.Work.EndDate</h4>
            </div>


            <div class="card-footer text-center">
                <a asp-page="Work"
                   class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
</div>

RealKruGameWebsite/Pages/Works/WorkEdit.cshtml
@page "{id:min(1)?}/{handler?}"
@model RealKruGameWebsite.Pages.Works.WorkEditModel
@{
    ViewData["Title"] = "Edit";
    // If an employee does not have a photo display noimage.png
    var photoPath = "~/workimages/" + (Model.Work.PhotoPath ?? "noimage.png");
    var pageHeader = Model.Work.Id > 0 ? "Edit" : "Add Work";
}
<h1>Notification Preferences</h1>
<div>
    <form method="post" asp-page-handler="UpdateNotificationPreferences">
        <div class="form-check">
            <input asp-for="Notify" class="form-check-input" />
            <label asp-for="Notify" class="form-check-label">
                Receive email notification when my details change
            </label>
        </div>
        <button type="submit" class="btn btn-primary">
            Update Notification Preferences
        </button>
        @if (Model.Message != null)
        {
            <div class="alert alert-primary">
                @Model.Message
            </div>
        }
    </form>

    <hr />
</div>

<h1>@pageHeader</h1>

<form method="post" class="mt-3" enctype="multipart/form-data"
      asp-page-handler="OnPost">
    @*Use hidden input elements to store employee id which
        we need when we submit the form*@
    <input hidden asp-for="Work.Id" />
    @*Store employee existing Photo Path in a hidden field*@
    <input hidden asp-for="Work.PhotoPath" />

    <div asp-validation-summary="All" class="text-danger"></div>

    @*asp-for tag helper takes care of displaying the existing
        data in the respective input elements*@
    <div class="form-group row">
        <label asp-for="Work.Title" class="col-sm-2 col-form-label">
        </label>
        <div class="col-sm-10">
            <input asp-for="Work.Title" class="form-control" placeholder="Title">
            <span asp-validation-for="Work.Title" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Work.Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Work.Description" class="form-control" placeholder="Description">
            <span asp-validation-for="Work.Description" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Work.StartDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Work.StartDate" class="form-control" placeholder="StartDate">
            <span asp-validation-for="Work.StartDate" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Work.EndDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Work.EndDate" class="form-control" placeholder="EndDate">
            <span asp-validation-for="Work.EndDate" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                @*Photo property type is IFormFile, so ASP.NET Core
        automatically creates a FileUpload control  *@
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">Click here to change photo</label>
            </div>
        </div>
    </div>

    @*Display the existing employee photo*@
    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-page="/Works/Work" class="btn btn-primary">Cancel</a>
        </div>
    </div>
    @*This jquery code is required to display the selected
        file name in the file upload controls*@
    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

    <partial name="_ValidationScriptsPartial"/>
    }
</form>